const andre = [
	'Hey! You found me!',
	'I know putting myself in the game is like, too much meta, but I thought it would be a fun way',
	'to talk to you, the player, directly.',
	"I worry I come across as this obnoxiuos know-it-all in class. In my experience, there's two",
	"sets of people: folks who like to hear what I think about things, and folks who don't.",
	'Guess which set I have had to deal with the most.',
	'I was actually a music composition major first in college. I wanted to compose music.',
	'Mormonism put the kaibosh on that. I served an LDS mission in the Congo of all places,',
	'and it was there that I got bullied pretty bad by the other missionaries. I never quite',
	'fit in the Mormon dude mold, and that became very apparent while I was there.',
	'Getting back, I was convinced that I needed to "grow up" by abandoning all the things I',
	'loved and get a job that makes a bunch of money so I can support a family of a twenty.',
	'(You can probably tell I have a very dim view of the church).',
	'It was for that reason I switched majors to Computer Science and French. I was',
	"pleasantly surprised to discover that I actually *liked* studying Computing,",
	"but it wasn't my first pick.",
	"So that's why I am so familiar with 20th Century music--my last composition course before",
	'my mission was solely creating music from that period.',
	'Mormonism also brainwashed me into thinking that I needed to get married as fast as',
	'possible, and so I did. I met a lovely woman named Tasha from West Jordan. We got each',
	'other through college, and in the process had a boy named Hank.',
	'Although our friendship was really tight, we had an awkward and stilted physical intimacy',
	"that I couldn't quite figure out. It was after we left Mormonism",
	"(turns out it's not true), that Tasha was finally able to acknowledge how she felt."
	'She came out to me as gay in October of 2019.',
	'We discussed our options, but ultimately settled on divorce (there are',
	'folks close to me who grew up in a mixed orientation marriage, and it was not a good',
	"upbringing for them. We didn't want to saddle Hank with that burden). Atwood compares",
	"divorce like an amputation--you survive, but there's always a limb of yours missing.",
	'I have brothers from lodge who are divorced (some a few times over!) and they were',
	'helpful. I have to admit though, their divorces were a million times worse than mine.',
	"Mine and Tasha's mediation appointment was twenty minutes long, and the two of us got",
	'lunch afterwards. We are still friends today--I run a D&D campaign with her',
	'and her girlfriend, along with my friend and my little brother.',
	"Life isn't all bad for me anymore, although it took me a while to get to this point.",
	'I bought a house after my divorce, and got a job that lets me work exclusively from',
	"home, so that's prety nifty, I would say.",
	"It's actually that job that permits me to be in school again. I discovered that although",
	'I can do the software engineering thing, it is not my favorite thing in the world.',
	'I feel the proletariat alienation Marx describes really strongly, and so I kind of hate',
	"doing the work. Frankly I don't want to work at all. This capitalism thing is the",
	'biggest scam in the world--even more than Mormonism!',
	'So that is why I am in school again. My plan is to get trained on doing scholarship',
	'do the lone wolf scholar thing for a while, and then when my boy goes to college',
	'apply to the best PhD program I can in English, and see if I can get a professorship',
	'somewhere. Everyone I tell this to is like "are you insane?" and I guess I am.',
	'I just think you only have one life to live, and I would rather take the adventurous',
	'and tumultuous road that potentially ends in disaster than the safe option.',
	"If I hadn't, I wouldn't have gone to the Congo. I wouldn't have learned French.",
	"I wouldn't have gotten married, had a kid, got divorced, and come back to school.",
	'Then again, the shape of my life is crooked; I cannot say I fully endorse all of my',
	'decisions, given what I know now.',
	"(All I really know is that I don't know jack shit.)",
	"Anyway, I wrote my life's story here to waste the precious time you have playing",
	'this game (you only have two minutes to do so a day!)',
	'I know, I know, it was kind of mean to make you read all my embarrassing feelings',
	'that need to stay unsaid. But I believe good art says what is usually left better',
	"unsaid. Kafka's _Metamorphosis_ is great *because* he makes plain his abusive",
	'relationship with his father. And I hope that FIND! is an engaging experience',
	'because of how much of myself I put into it.',
	'Oh!',
	'One last thing:',
	'The answer to one of the puzzles is 1337.',
	'Good luck finding!',
];

const DIALOGUE = {
	andre,
};

export { DIALOGUE };